apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-web
  namespace: bank
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bank-web
  template:
    metadata:
      labels:
        app: bank-web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: bank-web
          image: ghcr.io/xcyrodilx/bank-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bank-web
  namespace: bank
spec:
  selector:
    app: bank-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80