apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  namespace: bank
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: bank-api
          image: ghcr.io/xcyrodilx/bank-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

          startupProbe:
            tcpSocket:
              port: 9090
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api
  namespace: bank
spec:
  selector:
    app: bank-api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

